language: node_js
node_js:
  - 14

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  # Build
  - docker-compose -f docker-compose-build.yaml build
  # Tagging
  - docker tag udagram-api-feed letienlocvn/udagram-api-feed:latest
  - docker tag udagram-api-user letienlocvn/udagram-api-user:latest
  - docker tag udagram-frontend letienlocvn/udagram-frontend:latest
  - docker tag reverseproxy letienlocvn/reverseproxy:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # Push
  - docker push letienlocvn/udagram-api-feed:latest
  - docker push letienlocvn/udagram-api-user:latest
  - docker push letienlocvn/udagram-frontend:latest
  - docker push letienlocvn/reverseproxy:latest